language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

script:
- platformio ci --board=uno --lib=. $examples/EthernetShield_NoteOnOffEverySec/EthernetShield_NoteOnOffEverySec.ino;
